x-service-templates:
  api: &api # image: wellingtonbp/rinha_de_backend_ex:latest
    build: .
    environment:
      DB_CONN_URL: ecto://root:root@rinha-db/db
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '80MB'

  db: &db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '130MB'

  server: &server
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '60MB'

services:
  db:
    <<: *db
    container_name: rinha-db
    hostname: rinha-db

  api1:
    <<: *api
    container_name: api-1
    hostname: api-1
    depends_on:
      - db

  api2:
    <<: *api
    container_name: api-2
    hostname: api-2
    depends_on:
      - db

  lb:
    <<: *server
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2

networks:
  payment-processor:
    external: true
  rinha-backend-ex:
    driver: bridge
